version: "3"
services:
  zookeeper:
    container_name: zookeeper_1
    image: 'zookeeper:3.7.2'
    ulimits: 
      nofile:
        soft: 65536
        hard: 65536
    restart: on-failure
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    volumes: 
      - /var/lib/zookeeper:/var/lib/zookeeper
      - /var/log/zookeeper:/var/log/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181 #server.2=192.168.10.196:2888:3888;2181 server.3=192.168.10.197:2888:3888;2181
  
  registry:
    container_name: registry_1
    image: 'apache/nifi-registry:0.7.0'
    restart: on-failure
    hostname: registry
    depends_on:
        - nifi
    ports: 
        - "18443:18443"
    extra_hosts: 
      - "freeipa.zelines.local:192.168.10.188" 
      - "node-1.zelines.local:192.168.10.195" 
      - "node-2.zelines.local:192.168.10.196"
      - "node-3.zelines.local:192.168.10.197"
    environment:
      - LOG_LEVEL=INFO
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
      - NIFI_REGISTRY_FLOW_PROVIDER=file
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
      - AUTH=ldap
      - INITIAL_ADMIN_IDENTITY-uid=dwh,cn=users,cn=accounts,dc=zelines,dc=local
      - KEYSTORE_PATH=/opt/certs/keystore.jks 
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=123456
      - TRUSTSTORE_PATH=/opt/certs/truststore.jks
      - TRUSTSTORE_PASSWORD=123456
      - TRUSTSTORE_TYPE=JKS
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - LDAP_MANAGER_DN=uid=dwh,cn=users,cn=accounts,de=zelines,dc=local
      - LDAP_MANAGER_PASSWORD=11123333
      - LDAP_USER_SEARCH_BASE=cn=users,cn=accounts,de=zelines,de=local 
      - USER_SEARCH_FILTER=uid=(0}
      - LDAP_IDENTITY_STRATEGY=USE_DN
      - LDAP_URL=ldap://freeipa.zelines.local:389
    volumes:
      - ./certs:/opt/certs
      - ./nifi-registry/database:/opt/nifi-registry/nifi-registry-current/database
      - ./nifi-registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - nifi-registry:/opt/nifi-registry/nifi-registry-current/conf

  nifi:
    container_name: nifi
    image: 'apache/nifi:1.10.0'
    restart: on-failure
    hostname: nifi-1.zelines.local
    depends_on:
      - zookeeper
    ports:
      - '8444:8444'
      - '2882:2882'
      - '8080:8080'
    extra_hosts:
      - "freeipa.zelines.local:192.168.10.188"
      - "node-1.zelines.local:192.168.10.195" 
      - "node-2.zelines.local:192.168.10.196"
      - "node-3.zelines.local:192.168.10.197"
    environment:
      - AUTH=ldap
      - KEYSTORE_INITIAL_ADMIN_IDENTITY=uid=dwh,en-users,cn=accounts,de=zelines,dc=local
      - KEYSTORE_PATH=/opt/certs/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=123456
      - TRUSTSTORE_PATH=/opt/certs/truststore.jks
      - TRUSTSTORE_PASSWORD=123456
      - TRUSTSTORE_TYPE=JKS
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - LDAP_MANAGER_DN-uid=dwh-nifi, en-users, cn=accounts, dc-freeipa, de=local
      - LDAP_MANAGER_PASSWORD=123456
      - LDAP_USER_SEARCH_BASE=cn-users,en=accounts,dc=zelines,delocal
      - LDAP_IDENTITY_FILTER=uid={0}
      - LDAP_STRATEGY=USE_DN
      - LDAP_URL=ldap://freeipa.zelines.local:389
      - LDAP_WEB_HTTP_HOST=0.0.0.0
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8444
      - NIFI_WEB_PROXY_HOSTS=192.168.10.195:8444
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=2882
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_ZK_CONNECT_STRING=192.168.10.195:2181,192.168.10.196:2181,192.168.10.197:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_CLUSTER_NODE_ADDRESS=node-1.zelines.local
      - NIFI_SENSITIVE_PROPS_KEY=12345678901234567890A
      - NIFI_CLUSTER_PROTOCOL_IS_SECURE=true
    volumes:
      - ./certs:/opt/certs
      - /data/database_repository:/opt/nifi/nifi-current/database_repository
      - /data/flowfile_repo/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - /data/cont_repo/content_repository:/opt/nifi/nifi-current/content_repository
      - /data/prov_repo/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./state:/opt/nifi/nifi-current/state
      - ./logs:/opt/nifi/nifi-current/logs
      - nifi-conf:/opt/nifi/nifi-current/conf
volumes:
  nifi-conf:
    driver: local
  nifi-registry:
    driver: local
    
